### ISSUE TITLE
Does not subtract correctly?

### ISSUE THREAD

**Issue by bifacil** [xoofx/kalk#19]
What's the result of `3-1`?

![image](https://user-images.githubusercontent.com/4572969/101267603-c19fed00-375a-11eb-8548-e918cdc7de51.png)

I am not sure if this is the expected result.

**Comment by xoofx** [comment]
No that's a bug. The parser is doing something special with `-x`/`-1` but I don't remember the details why it triggers in that case. I will check that asap.

**Comment by xoofx** [comment]
That should be fixed in the upcoming `0.3.1`

The original reasoning was to allow to pass -2 to a function parameter without parenthesis e.g `abs -2` but it can bring too much confusion if you start to have `x-2` in that case. So I have removed the ability to pass a unary negative without parenthesis to a function.
