### ISSUE TITLE
Problem with certain ARM intrinsics

### ISSUE THREAD

**Issue by emoon** [xoofx/kalk#41]
If I write something like this

```
vmlal_s16(int4(0,0,0,0), int4(2,2,2,2), int4(1,2,3,4))
```
The result will be
```
out(2, 0, 4, 0);
```
Which is unexpected given https://developer.arm.com/architectures/instruction-sets/intrinsics/vmlal_s16 that the result should be `a + b * c` where the result gets expanded to `int32x4` in this case.

**Comment by xoofx** [comment]
The current code was trying to copy the smallest size even if the argument didn't match. In practice, you should replace the `int4` with `short4` in order to make it working `vmlal_s16(int4(0,0,0,0), short4(2,2,2,2), short4(1,2,3,4))`.

#42 is going to be more restrictive in case the vector argument types doesn't match in size and will generate an error.
